### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by chenyj8** [pereiramemo/AGS-and-ACN-tools#4]
Hi Emiliano,

Thank you for this excellent tool.

I am trying to run the example dataset in my laptop. But I found that SortmerRNA failed because of the "-m" option. It looks like my laptop memory is higher than the default, so the SortmerRNA failed. Any ideas?

![image](https://user-images.githubusercontent.com/48304249/76049928-7fbfed00-5f23-11ea-9887-1587bcf93853.png)

**Comment by pereiramemo** [comment]
Dear Chenyj8,

Thanks for using the AGS-ACN tools. I hope you find these useful. 
The memory usage in SortMeRNA (using the -m parameter) is set to 1000 Mbytes. You can see this in the configuration file https://github.com/pereiramemo/AGS-and-ACN-tools/blob/master/code/acn_conf

How much RAM do you have in your computer? 
Just in case: please try to restart the docker service (service docker restart) and run it again.

Cheers,

Emiliano

**Comment by chenyj8** [comment]
My computer has a 16 GB memory. How do I set the -m parameter?

**Comment by chenyj8** [comment]
Thank you. My computer has a 16 GB RAM, but how do I set the -m parameter?

**Comment by chenyj8** [comment]
Thank you. My computer has a 16 GB RAM, but how do I set the -m parameter?

**Comment by pereiramemo** [comment]
Thanks for the prompt answer.
In the current version, the memory is fixed; however, I can update the acn image to have it as a parameter. I'll let you know when the image is uploaded.

Just to make sure: Did you try to run this command al least few times (i.e., after rebooting your computer or restarting the docker service), and consistently got this error? 

Cheers,

**Comment by chenyj8** [comment]
Yes, I tried it several times these days. I just tried once, the sormerna still failed.

![image](https://user-images.githubusercontent.com/48304249/76277629-819cef80-6246-11ea-8046-7b02104421ec.png)

**Comment by pereiramemo** [comment]
Did you just copied-pasted this command from the wiki page?
Could you please try to run it with the evlaue quoted (i.e., "1e-10").

Thanks,

**Comment by chenyj8** [comment]
Yes, I copied-pasted this command from the tutorial.
I just tried adding quoted but still got the same error message.

**Comment by pereiramemo** [comment]
How can you didn't get the warning in the first place (when you to the memory error)? 
Was everything ran in the same exact way?

Could you please provide me with the command you used (not the image), so that I can carefully see all the characters?
Thanks,

**Comment by chenyj8** [comment]
Sorry for the confusion.

So I first tried this and got the error message.
```bash
./run_acn.sh tara_023_srf_ags_output/tara_023_srf_FBL.fna tara_023_srf_ags_output/tara_023_srf_ags.tsv tara_023_srf_acn_output --sample_name tara_023_srf --evalue 1e-10 --min_identity 80 --min_length 30 --verbose t --overwrite t --nslots 2 --save_complementary_data t
WARN: Unknown option (ignored): --min_identity
sormerna failed
````
Then I removed the --min_identity and got this
```bash
./run_acn.sh tara_023_srf_ags_output/tara_023_srf_FBL.fna tara_023_srf_ags_output/tara_023_srf_ags.tsv tara_023_srf_acn_output --sample_name tara_023_srf --evalue 1e-10 --min_length 30 --verbose t --overwrite t --nslots 2 --save_complementary_data t
WARN: Unknown option (ignored): --min_length
sormerna failed
````
I removed the --min_length and got the "sormerna failed" message
````bash
./run_acn.sh tara_023_srf_ags_output/tara_023_srf_FBL.fna tara_023_srf_ags_output/tara_023_srf_ags.tsv tara_023_srf_acn_output --sample_name tara_023_srf --evalue 1e-10 --verbose t --overwrite t --nslots 2 --save_complementary_data t
Identifying 16S rRNA genes ...

ERROR: -m [INT] must not exceed 1989 (Mbyte).

sormerna failed
````
Lastly, I tried adding a quoted evalue but still got the same error message
````bash
./run_acn.sh tara_023_srf_ags_output/tara_023_srf_FBL.fna tara_023_srf_ags_output/tara_023_srf_ags.tsv tara_023_srf_acn_output --sample_name tara_023_srf --evalue "1e-10" --verbose t --overwrite t --nslots 2 --save_complementary_data t
Identifying 16S rRNA genes ...

ERROR: -m [INT] must not exceed 1989 (Mbyte).

sormerna failed
````

**Comment by pereiramemo** [comment]
Ok, thanks. 
I'm thinking this could be related to the Mac OS ...
Can you try the tools on a Linux computer?

**Comment by pereiramemo** [comment]
I will have to continue tomorrow. 
Cheers,

**Comment by chenyj8** [comment]
No problem. I will try it on a Linux platform tomorrow and keep you posted. Thank you very much.

**Comment by chenyj8** [comment]
Hi,

I tried it on the Linux installed on my Mac, now it seems that "--min_identity" and "--min_length" are working but the "-m" problem still exists. The "-m" is fixed as 1000 Mbytes, so the program should only use a maximum of 1000 Mbytes no matter how much RAM my computer has. 
```bash
chenyj@ubuntu:~/Documents/software/AGS-and-ACN-tools$ ./run_acn.sh tara_023_srf_ags_output/tara_023_srf_FBL.fna tara_023_srf_ags_output/tara_023_srf_ags.tsv tara_023_srf_acn_output --sample_name tara_023_srf --evalue 1e-10 --min_identity 80 --min_length 30 --verbose t --overwrite t --nslots 3 --save_complementary_data t
Identifying 16S rRNA genes ...

ERROR: -m [INT] must not exceed 1981 (Mbyte).

sormerna failed
```

**Comment by pereiramemo** [comment]
Ok.Thanks for the message. 
As I mentioned, I can update the code to have the memory usage as a parameter (it will be a useful feature). I'll write you back when the new images are uploaded.

I'm sorry for the inconvenience. I think there is something else going on here. I have to test this in a Mac OS, which I don't have right now.

**Comment by pereiramemo** [comment]
The docker image to compute the ACN now includes the --smrna_mem flag to set the memory usage when running SortMeRNA.

All the best,
